name: Most used
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.languages.svg
  token: ${{ secrets.METRICS_TOKEN }}
  plugin_languages: yes
  plugin_languages_ignored: html, css
  plugin_languages_limit: 4
